// Generated by CoffeeScript 1.12.7
(function() {
  var a1, bitlist, cube, date, greatlyImproved, kids, mood, singers, singing, song, square;

  square = (function(_this) {
    return function(x) {
      return x * x;
    };
  })(this);

  cube = (function(_this) {
    return function(x) {
      return square(x) * x;
    };
  })(this);

  a1 = cube(3);

  console.log("I am " + a1 + " years old.");

  song = ["do", "re", "mi", "fa", "so"];

  singers = {
    Jagger: "Rock",
    Elvis: "Roll"
  };

  bitlist = [1, 0, 1, 0, 0, 1, 1, 1, 0];

  kids = {
    brother: {
      name: "Max",
      age: 11
    },
    sister: {
      name: "Ida",
      age: 9
    }
  };

  console.log('aaaa1', song);

  console.log('aaaa2', singers);

  console.log('aaaa3', bitlist);

  console.log('aaaa4', kids);

  $('#app').addClass("active");

  singing = true;

  greatlyImproved = ['happy', 'good'];

  if (singing) {
    mood = greatlyImproved;
  }

  console.log('mood', mood);

  date = friday ? sue : jill;

  if (happy && knowsIt) {
    clapsHands();
    chaChaCha();
  } else {
    showIt();
  }

}).call(this);
